LIBS = -lglut -lGLU -lGL -lsndfile -lportaudio -lGLEW -lglfw -lfftw3

all: player player3

player: player.cpp 
	g++ -o player player.cpp $(LIBS)

player3: player3.cpp 
	g++ -o player3 player3.cpp $(LIBS)
